### ISSUE TITLE
Issue on Laravel 6

### ISSUE THREAD

**Issue by jp-jsr-group** [danielme85/laravel-geoip2#1]
Can't update composer after upgrading to Laravel 6.

![image](https://user-images.githubusercontent.com/50224853/64774818-80d11c80-d587-11e9-86d3-1c7f41f9271f.png)

**Comment by danielme85** [comment]
I just updated the composer file on dev-master, give that a try. 
And please let me know if there are any issues or if it just works :)

**Comment by jp-jsr-group** [comment]
I added the         `"illuminate/support": ">=5.4"` on composer.json
thanks it works now.

![image](https://user-images.githubusercontent.com/50224853/64831808-eebe2800-d609-11e9-8d42-28095c2423ad.png)
