### ISSUE TITLE
An issue on Downloader.php

### ISSUE THREAD

**Issue by poinchy** [danielme85/laravel-geoip2#3]
I found an issue on danielme85/laravel-geoip2/src/Commands/Downloader.php .

I don't use **GeoLite2-City.mmdb**, but **GeoIP2-Country.mmdb**.
I changed the downloadUrl and filename on config/geoip2.php.

But when I try to get country code like below
`$reader = Reader::connect();` ,
I get 500 error.

I read _danielme85/laravel-geoip2/src/Geoip2Connector.php_ , then I found that this error occurs because **$dbFilePath** does not exist.

Then I read _danielme85/laravel-geoip2/src/Commands/Downloader.php_, then I found that "function extract()" does not work correctly because **$from** variable does not refer to the config file.

I changed this description
`$from = "{$this->dbFolder}/tmp/extracted/$folder/GeoLite2-City.mmdb";`
to 
`$from = "{$this->dbFolder}/tmp/extracted/$folder/$this->dbFileName";`.
After this fix, it works correctly.

Could you fix Downloader.php ?
Thank you

**Comment by danielme85** [comment]
Hi, thank you for the heads up.
I'll take a look at it when I have some time, I'm sure this could use an update and some testing with newer Laravel.

**Comment by danielme85** [comment]
Oh I see, sorry: that's a hardcoded string there. 

Do you want to submit a PR for this fix? So you get the credit you deserve 👍 
If not I'll push this fix asap.

Thank you again!
Sorry for the delay, this is a silly mistake and a simple fix!

**Comment by poinchy** [comment]
Thank you.
I just sent a pull request. 
Please check it out.

**Comment by danielme85** [comment]
fixed by #4
