### ISSUE TITLE
About the dependency with "guzzlehttp/guzzle"

### ISSUE THREAD

**Issue by poinchy** [danielme85/laravel-geoip2#6]
Hi.

Since laravel8 was recently released I attempted to install it.

According to the [installation guide](https://laravel.com/docs/8.x/upgrade), I need to set up the following dependencies, so I put them in the "composer.json".

> guzzlehttp/guzzle to ^7.0.1
> facade/ignition to ^2.3.6
> laravel/framework to ^8.0
> nunomaduro/collision to ^5.0
> phpunit/phpunit to ^9.0

And when I try to run "composer update", I get the following error:
> $ composer update
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Your requirements could not be resolved to an installable set of packages.
>
> Problem 1
>    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].
>    - danielme85/laravel-geoip2 v1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
>    - danielme85/laravel-geoip2 v1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
>    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
>    - Installation request for danielme85/laravel-geoip2 ^1.0 -> satisfiable by danielme85/laravel-geoip2[v1.0].

Does laravel-geoip2 not support guzzlehttp/guzzle 7.0.1?
Is it possible to change the guzzlehttp/guzzle dependency in laravel-geoip2 to 7.0.1?

Thank you.

**Comment by danielme85** [comment]
Hi @poinchy,
I'll take a look tonight. Hopefully just need to update the composer file.
Hmm, they seem to have dropped PHP 5 support in Guzzle 7.
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

I might split this project into legacy PHP5/Guzzle6 and then make the "default" PHP7/Guzzle7.

Thank you for the heads-up, I have been thinking about starting to test my projects with Laravel 8, you beat me to it 👍 
-dan

**Comment by danielme85** [comment]
Just pushed an updated composer file to the dev branch, you could give that a try?

**Comment by danielme85** [comment]
Merged dev branch into master b59922f56bed998c394aad03e1affe3a56589e03

**Comment by poinchy** [comment]
Thank you so much for your prompt response!
I was able to install Laravel 8 successfully.

**Comment by danielme85** [comment]
No problem, again thanks for the heads-up!
